Add explosion( pos, mag, attacker )
CFC-Servers/cfc_admin_core pull request #1
Opened 2021-06-26 20:40 UTC by StrawWagen

add explosion with changeable attacker, will allow explosions to be "created" by entities instead of the e2 owner

2021-10-10 18:08 UTC, sarahsturgeon requested changes

2021-10-10 18:08 UTC, sarahsturgeon commented on lua/entities/gmod_wire_expression2/core/custom/admincore.lua
> +end
Is `allowexplosion` defined somewhere?

```suggestion
e2function void explosion(vector pos, number mag, entity attacker)
	if not self.player:IsAdmin() and not allowexplosion then return end

	local explode = ents.Create( "env_explosion" )
	explode:SetPos( Vector( pos[1], pos[2], pos[3] ) )
	explode:SetOwner( attacker )
	explode:Spawn()
	explode:SetKeyValue( "iMagnitude", mag )
	explode:Fire( "Explode", 0, 0 )
end

```

2021-10-11 23:49 UTC, StrawWagen commented on lua/entities/gmod_wire_expression2/core/custom/admincore.lua
> +end
allowexplosion is defined by a concmd, lets explosion stuff be enabled/disabled

2021-11-25 09:37 UTC, brandonsturgeon approved these changes

2021-11-25 09:37 UTC, merged